name: playground
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  confetti: ^0.7.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.19.0
  flutter_svg: ^2.0.7
  lottie: ^2.5.0
  print_color: ^3.0.5
  provider: ^6.0.5
  rive: ^0.11.5
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/lottie/
    - assets/rive/
